[package]
name = "cargo-sample"
version = "1.0.0"
edition = "2021"
description = "A simple Rust web application that uses a few dependencies"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
